# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-MT376R2V1H0"
BBFILE_PATTERN_meta-MT376R2V1H0 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-MT376R2V1H0 = "30"

LAYERDEPENDS_meta-MT376R2V1H0 = "variscite-bsp"
LAYERSERIES_COMPAT_meta-MT376R2V1H0 = "scarthgap"
